/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.pawel.domagala._rejestracja_i_logowanie_domagalapawel;


import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
/**
 *
 * @author domag
 */
public class logowanie_i_rejestracja extends javax.swing.JFrame {

    /**
     * Creates new form logowanie_i_rejestracja
     */
    public logowanie_i_rejestracja() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneRejestracja = new javax.swing.JTabbedPane();
        jPanelRejestracja = new javax.swing.JPanel();
        jLabelRejestracja = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelConPass = new javax.swing.JLabel();
        jButtonRejestracja = new javax.swing.JButton();
        jLabelUsernameBlad = new javax.swing.JLabel();
        jLabelEmailBlad = new javax.swing.JLabel();
        jLabelUsernameBlad2 = new javax.swing.JLabel();
        jLabelConPassBlad = new javax.swing.JLabel();
        jLabelPassBlad = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jPasswordFieldConPass = new javax.swing.JPasswordField();
        jPanelLogowanie = new javax.swing.JPanel();
        jButtonZaloguj = new javax.swing.JButton();
        jLabelRejestracja1 = new javax.swing.JLabel();
        jLabelEmail2 = new javax.swing.JLabel();
        jTextFieldEmail2 = new javax.swing.JTextField();
        jLabelPassword2 = new javax.swing.JLabel();
        jTextFieldPassword2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelRejestracja.setBackground(new java.awt.Color(255, 255, 255));

        jLabelRejestracja.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelRejestracja.setText("Rejestracja");

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelUsername.setText("Username");

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEmail.setText("Email");

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPassword.setText("Password");

        jLabelConPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelConPass.setText("Confirm Password");

        jButtonRejestracja.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRejestracja.setText("Rejestracja");
        jButtonRejestracja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRejestracjaActionPerformed(evt);
            }
        });

        jLabelUsernameBlad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelEmailBlad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelUsernameBlad2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelConPassBlad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelPassBlad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPasswordFieldPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPasswordFieldConPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelRejestracjaLayout = new javax.swing.GroupLayout(jPanelRejestracja);
        jPanelRejestracja.setLayout(jPanelRejestracjaLayout);
        jPanelRejestracjaLayout.setHorizontalGroup(
            jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRejestracja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsernameBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmailBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelConPass, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addComponent(jButtonRejestracja)
                    .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                        .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldConPass, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelConPassBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                    .addGap(354, 354, 354)
                    .addComponent(jLabelUsernameBlad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        jPanelRejestracjaLayout.setVerticalGroup(
            jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jLabelUsernameBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmailBlad, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                        .addComponent(jLabelPassBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                        .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabelConPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                        .addComponent(jPasswordFieldConPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelConPassBlad, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRejestracja)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRejestracjaLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jLabelUsernameBlad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(257, 257, 257)))
        );

        jTabbedPaneRejestracja.addTab("Rejestracja", jPanelRejestracja);

        jPanelLogowanie.setBackground(new java.awt.Color(255, 255, 255));

        jButtonZaloguj.setBackground(new java.awt.Color(255, 255, 255));
        jButtonZaloguj.setText("Zaloguj");

        jLabelRejestracja1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelRejestracja1.setText("Logowanie");

        jLabelEmail2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEmail2.setText("Email");

        jTextFieldEmail2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelPassword2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPassword2.setText("Password");

        jTextFieldPassword2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelLogowanieLayout = new javax.swing.GroupLayout(jPanelLogowanie);
        jPanelLogowanie.setLayout(jPanelLogowanieLayout);
        jPanelLogowanieLayout.setHorizontalGroup(
            jPanelLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogowanieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRejestracja1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmail2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail2)
                    .addComponent(jLabelPassword2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPassword2)
                    .addGroup(jPanelLogowanieLayout.createSequentialGroup()
                        .addComponent(jButtonZaloguj)
                        .addGap(0, 488, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLogowanieLayout.setVerticalGroup(
            jPanelLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogowanieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRejestracja1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmail2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonZaloguj)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPaneRejestracja.addTab("Logowanie", jPanelLogowanie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRejestracjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRejestracjaActionPerformed
        login();
        email();
        pass();
        conpass();
    }//GEN-LAST:event_jButtonRejestracjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logowanie_i_rejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logowanie_i_rejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logowanie_i_rejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logowanie_i_rejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logowanie_i_rejestracja().setVisible(true);
            }
        });
    }
    
    private void login(){
        if(jTextFieldUsername.getText().length() <2 || jTextFieldUsername.getText().length() >20){
            jLabelUsernameBlad.setText("Wpisano zły login");
        }else if(jTextFieldUsername.getText().length() >2 || jTextFieldUsername.getText().length() <20){
            jLabelUsernameBlad.setText("");  
        }
        
        char[] chars = jTextFieldUsername.getText().toCharArray();
        for (char word : chars) {
            if(!Character.isLetter(word)) {
               jLabelUsernameBlad.setText("Wpisano zły login"); 
            }
        }  
    }
    
    private void email(){
        
    }
    
    private void pass(){
        if(jPasswordFieldPass.getText().length() <4){
            jLabelPassBlad.setText("Wpisano złe hasło");
        }else if(jPasswordFieldPass.getText().length() >4){
            jLabelPassBlad.setText("");  
        }
    }
    
    private void conpass(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRejestracja;
    private javax.swing.JButton jButtonZaloguj;
    private javax.swing.JLabel jLabelConPass;
    private javax.swing.JLabel jLabelConPassBlad;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmail2;
    private javax.swing.JLabel jLabelEmailBlad;
    private javax.swing.JLabel jLabelPassBlad;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword2;
    private javax.swing.JLabel jLabelRejestracja;
    private javax.swing.JLabel jLabelRejestracja1;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsernameBlad;
    private javax.swing.JLabel jLabelUsernameBlad2;
    private javax.swing.JPanel jPanelLogowanie;
    private javax.swing.JPanel jPanelRejestracja;
    private javax.swing.JPasswordField jPasswordFieldConPass;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTabbedPane jTabbedPaneRejestracja;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmail2;
    private javax.swing.JTextField jTextFieldPassword2;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
