/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.waluciarz;

/**
 *
 * @author domagalapawel
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    private DownloadFromHTML dfhtml;
    private saveToFile stf;
    
    public main() {
        initComponents();
        setLocationRelativeTo(null);
        jTFwynikSell.setEditable(false);
        jTFwynikBuy.setEditable(false);
        dfhtml = new DownloadFromHTML();
        stf = new saveToFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        MainLabel = new javax.swing.JLabel();
        jTFzloty = new javax.swing.JTextField();
        jCBwalutaSell = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jBsell = new javax.swing.JButton();
        jTFwynikSell = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTFwaluta = new javax.swing.JTextField();
        MainLabel1 = new javax.swing.JLabel();
        jBbuy = new javax.swing.JButton();
        jTFwynikBuy = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCBwalutaBuy = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 63, 66));

        MainLabel.setFont(new java.awt.Font("Z003", 1, 48)); // NOI18N
        MainLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainLabel.setText("Waluciarz");
        MainLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTFzloty.setBackground(new java.awt.Color(70, 73, 76));
        jTFzloty.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jTFzloty.setForeground(new java.awt.Color(255, 255, 255));
        jTFzloty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFzloty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFzlotyActionPerformed(evt);
            }
        });

        jCBwalutaSell.setBackground(new java.awt.Color(70, 73, 76));
        jCBwalutaSell.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jCBwalutaSell.setForeground(new java.awt.Color(255, 255, 255));
        jCBwalutaSell.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "CHF", "JPY" }));
        jCBwalutaSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBwalutaSellActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("zł         na");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jBsell.setBackground(new java.awt.Color(78, 80, 81));
        jBsell.setForeground(new java.awt.Color(255, 255, 255));
        jBsell.setText("Oblicz");
        jBsell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsellActionPerformed(evt);
            }
        });

        jTFwynikSell.setBackground(new java.awt.Color(70, 73, 76));
        jTFwynikSell.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jTFwynikSell.setForeground(new java.awt.Color(255, 255, 255));
        jTFwynikSell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFwynikSell.setText("-");
        jTFwynikSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFwynikSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MainLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFzloty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBwalutaSell, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBsell, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTFwynikSell, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(MainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFzloty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBwalutaSell, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFwynikSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sprzedarz", jPanel1);

        jPanel2.setBackground(new java.awt.Color(60, 63, 66));

        jTFwaluta.setBackground(new java.awt.Color(70, 73, 76));
        jTFwaluta.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jTFwaluta.setForeground(new java.awt.Color(255, 255, 255));
        jTFwaluta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFwaluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFwalutaActionPerformed(evt);
            }
        });

        MainLabel1.setFont(new java.awt.Font("Z003", 1, 48)); // NOI18N
        MainLabel1.setForeground(new java.awt.Color(255, 255, 255));
        MainLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainLabel1.setText("Waluciarz");
        MainLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jBbuy.setBackground(new java.awt.Color(78, 80, 81));
        jBbuy.setForeground(new java.awt.Color(255, 255, 255));
        jBbuy.setText("Oblicz");
        jBbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuyActionPerformed(evt);
            }
        });

        jTFwynikBuy.setBackground(new java.awt.Color(70, 73, 76));
        jTFwynikBuy.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jTFwynikBuy.setForeground(new java.awt.Color(255, 255, 255));
        jTFwynikBuy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFwynikBuy.setText("-");
        jTFwynikBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFwynikBuyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("na        zł");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jCBwalutaBuy.setBackground(new java.awt.Color(70, 73, 76));
        jCBwalutaBuy.setFont(new java.awt.Font("Z003", 0, 24)); // NOI18N
        jCBwalutaBuy.setForeground(new java.awt.Color(255, 255, 255));
        jCBwalutaBuy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "CHR", "JPY" }));
        jCBwalutaBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBwalutaBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBwalutaBuy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFwynikBuy, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jTFwaluta, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jBbuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(MainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTFwaluta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBwalutaBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBbuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFwynikBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kupno", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFzlotyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFzlotyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFzlotyActionPerformed

    private void jCBwalutaSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBwalutaSellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBwalutaSellActionPerformed

    private void jBsellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsellActionPerformed
        dfhtml.setWybor(true);
        sell();
    }//GEN-LAST:event_jBsellActionPerformed

    private void jTFwynikSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFwynikSellActionPerformed
        
    }//GEN-LAST:event_jTFwynikSellActionPerformed

    private void jTFwalutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFwalutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFwalutaActionPerformed

    private void jCBwalutaBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBwalutaBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBwalutaBuyActionPerformed

    private void jBbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuyActionPerformed
        dfhtml.setWybor(false);
        buy();
    }//GEN-LAST:event_jBbuyActionPerformed

    private void jTFwynikBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFwynikBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFwynikBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    
    private void sell(){
        float amount = Float.parseFloat(jTFzloty.getText());
        String currency = jCBwalutaSell.getSelectedItem().toString();
        float price = dfhtml.DFHTML(currency);
        float result = amount*price;
        jTFwynikSell.setText(""+result);
        stf.saveToFile("sell", currency, amount, result, price);
    }
    
    private void buy(){
        float amount = Float.parseFloat(jTFwaluta.getText());
        String currency = jCBwalutaBuy.getSelectedItem().toString();
        float price = dfhtml.DFHTML(currency);
        float result = amount*price;
        jTFwynikBuy.setText(""+result);
        stf.saveToFile("buy", currency, amount, result, price);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JLabel MainLabel1;
    private javax.swing.JButton jBbuy;
    private javax.swing.JButton jBsell;
    private javax.swing.JComboBox<String> jCBwalutaBuy;
    private javax.swing.JComboBox<String> jCBwalutaSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFwaluta;
    private javax.swing.JTextField jTFwynikBuy;
    private javax.swing.JTextField jTFwynikSell;
    private javax.swing.JTextField jTFzloty;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
