/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.pawel.domagala.domagala_pawel_12przeliczaniejednostek;

import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.io.*; //* - wszystkie klasy/biblioteki
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


/**
 *
 * @author domag
 */
public class PrzeliczanieJednostek extends javax.swing.JFrame {

    /**
     * Creates new form PrzeliczanieJednostek
     */
    public PrzeliczanieJednostek() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pd_buttonGroupDlugosci = new javax.swing.ButtonGroup();
        pd_buttonGroupTemperatura = new javax.swing.ButtonGroup();
        pd_jPanel = new javax.swing.JPanel();
        pd_jLabelMain = new javax.swing.JLabel();
        pd_jTabbedPaneMain = new javax.swing.JTabbedPane();
        pd_jPanelDlugosci = new javax.swing.JPanel();
        pd_jLabelWartJednDlug = new javax.swing.JLabel();
        pd_jTextFieldWpiszDlug = new javax.swing.JTextField();
        pd_jLabelPrzelJednDlug = new javax.swing.JLabel();
        pd_jRadioButtonMM = new javax.swing.JRadioButton();
        pd_jRadioButtonCM = new javax.swing.JRadioButton();
        pd_jRadioButtonDM = new javax.swing.JRadioButton();
        pd_jRadioButtonM = new javax.swing.JRadioButton();
        pd_jRadioButtonKM = new javax.swing.JRadioButton();
        pd_jSeparator1 = new javax.swing.JSeparator();
        pd_jLabelMM = new javax.swing.JLabel();
        pd_jTextFieldMM = new javax.swing.JTextField();
        pd_jLabelCM = new javax.swing.JLabel();
        pd_jTextFieldCM = new javax.swing.JTextField();
        pd_jLabelM = new javax.swing.JLabel();
        pd_jTextFieldM = new javax.swing.JTextField();
        pd_jLabelKM = new javax.swing.JLabel();
        pd_jTextFieldKM = new javax.swing.JTextField();
        pd_jButtonPrzelicz = new javax.swing.JButton();
        pd_jTextFieldDM = new javax.swing.JTextField();
        pd_jLabelDM = new javax.swing.JLabel();
        pd_jPanelTemperatury = new javax.swing.JPanel();
        pd_jLabelWartJednTemp = new javax.swing.JLabel();
        pd_jTextFieldWpiszTemp = new javax.swing.JTextField();
        pd_jLabelPrzelJednTemp = new javax.swing.JLabel();
        pd_jRadioButtonC = new javax.swing.JRadioButton();
        pd_jRadioButtonK = new javax.swing.JRadioButton();
        pd_jRadioButtonF = new javax.swing.JRadioButton();
        pd_jSeparator2 = new javax.swing.JSeparator();
        pd_jLabelC = new javax.swing.JLabel();
        pd_jTextFieldC = new javax.swing.JTextField();
        pd_jLabelK = new javax.swing.JLabel();
        pd_jTextFieldK = new javax.swing.JTextField();
        pd_jButtonPrzeliczTemp = new javax.swing.JButton();
        pd_jTextFieldF = new javax.swing.JTextField();
        pd_jLabelF = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        pd_jMenuPlik = new javax.swing.JMenu();
        pd_jMenuItemHistoria = new javax.swing.JMenuItem();
        pd_jMenuItemZamknij = new javax.swing.JMenuItem();
        pd_jMenuOprogramie = new javax.swing.JMenu();
        pd_jMenuItemOpis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pd_jPanel.setBackground(new java.awt.Color(51, 51, 51));

        pd_jLabelMain.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        pd_jLabelMain.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelMain.setText("Przeliczanie jednostek");

        pd_jTabbedPaneMain.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTabbedPaneMain.setInheritsPopupMenu(true);

        pd_jPanelDlugosci.setBackground(new java.awt.Color(102, 102, 102));
        pd_jPanelDlugosci.setForeground(new java.awt.Color(255, 255, 255));

        pd_jLabelWartJednDlug.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelWartJednDlug.setText("Wartość jednostki");

        pd_jTextFieldWpiszDlug.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldWpiszDlug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldWpiszDlugActionPerformed(evt);
            }
        });

        pd_jLabelPrzelJednDlug.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelPrzelJednDlug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelPrzelJednDlug.setText("Przeliczana jednostka");

        pd_jRadioButtonMM.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupDlugosci.add(pd_jRadioButtonMM);
        pd_jRadioButtonMM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonMM.setText("mm");
        pd_jRadioButtonMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jRadioButtonMMActionPerformed(evt);
            }
        });

        pd_jRadioButtonCM.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupDlugosci.add(pd_jRadioButtonCM);
        pd_jRadioButtonCM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonCM.setText("cm");

        pd_jRadioButtonDM.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupDlugosci.add(pd_jRadioButtonDM);
        pd_jRadioButtonDM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonDM.setText("dm");

        pd_jRadioButtonM.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupDlugosci.add(pd_jRadioButtonM);
        pd_jRadioButtonM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonM.setText("m");

        pd_jRadioButtonKM.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupDlugosci.add(pd_jRadioButtonKM);
        pd_jRadioButtonKM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonKM.setText("km");

        pd_jLabelMM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelMM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelMM.setText("Milimetrów");

        pd_jTextFieldMM.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldMMActionPerformed(evt);
            }
        });

        pd_jLabelCM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelCM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelCM.setText("Centymetrów");

        pd_jTextFieldCM.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldCMActionPerformed(evt);
            }
        });

        pd_jLabelM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelM.setText("Metrów");

        pd_jTextFieldM.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldMActionPerformed(evt);
            }
        });

        pd_jLabelKM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelKM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelKM.setText("Kilometrów");

        pd_jTextFieldKM.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldKMActionPerformed(evt);
            }
        });

        pd_jButtonPrzelicz.setBackground(new java.awt.Color(102, 102, 102));
        pd_jButtonPrzelicz.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButtonPrzelicz.setText("Przelicz");
        pd_jButtonPrzelicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonPrzeliczActionPerformed(evt);
            }
        });

        pd_jTextFieldDM.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldDMActionPerformed(evt);
            }
        });

        pd_jLabelDM.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelDM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelDM.setText("Decymetrów");

        javax.swing.GroupLayout pd_jPanelDlugosciLayout = new javax.swing.GroupLayout(pd_jPanelDlugosci);
        pd_jPanelDlugosci.setLayout(pd_jPanelDlugosciLayout);
        pd_jPanelDlugosciLayout.setHorizontalGroup(
            pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pd_jLabelWartJednDlug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pd_jTextFieldWpiszDlug, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                                .addComponent(pd_jRadioButtonMM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pd_jRadioButtonCM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pd_jRadioButtonDM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pd_jRadioButtonM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pd_jRadioButtonKM))
                            .addComponent(pd_jLabelPrzelJednDlug, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pd_jSeparator1))
                    .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(pd_jButtonPrzelicz))
                            .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pd_jTextFieldM)
                                            .addComponent(pd_jLabelM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pd_jLabelKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pd_jTextFieldKM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pd_jTextFieldMM)
                                            .addComponent(pd_jLabelMM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pd_jTextFieldCM)
                                            .addComponent(pd_jLabelCM, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pd_jLabelDM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pd_jTextFieldDM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pd_jPanelDlugosciLayout.setVerticalGroup(
            pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jLabelWartJednDlug)
                    .addComponent(pd_jLabelPrzelJednDlug))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jTextFieldWpiszDlug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jRadioButtonMM)
                    .addComponent(pd_jRadioButtonCM)
                    .addComponent(pd_jRadioButtonM)
                    .addComponent(pd_jRadioButtonKM)
                    .addComponent(pd_jRadioButtonDM))
                .addGap(14, 14, 14)
                .addComponent(pd_jButtonPrzelicz)
                .addGap(19, 19, 19)
                .addComponent(pd_jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pd_jLabelMM)
                    .addComponent(pd_jLabelCM, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jLabelDM)
                    .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pd_jTextFieldCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pd_jTextFieldDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pd_jTextFieldMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelDlugosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pd_jPanelDlugosciLayout.createSequentialGroup()
                        .addComponent(pd_jLabelM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pd_jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pd_jPanelDlugosciLayout.createSequentialGroup()
                        .addComponent(pd_jLabelKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pd_jTextFieldKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pd_jTabbedPaneMain.addTab("Jednostki długości", pd_jPanelDlugosci);

        pd_jPanelTemperatury.setBackground(new java.awt.Color(102, 102, 102));

        pd_jLabelWartJednTemp.setBackground(new java.awt.Color(102, 102, 102));
        pd_jLabelWartJednTemp.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelWartJednTemp.setText("Wartość jednostki");

        pd_jTextFieldWpiszTemp.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldWpiszTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldWpiszTempActionPerformed(evt);
            }
        });

        pd_jLabelPrzelJednTemp.setBackground(new java.awt.Color(102, 102, 102));
        pd_jLabelPrzelJednTemp.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelPrzelJednTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelPrzelJednTemp.setText("Przeliczana jednostka");

        pd_jRadioButtonC.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupTemperatura.add(pd_jRadioButtonC);
        pd_jRadioButtonC.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonC.setText("°C");
        pd_jRadioButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jRadioButtonCActionPerformed(evt);
            }
        });

        pd_jRadioButtonK.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupTemperatura.add(pd_jRadioButtonK);
        pd_jRadioButtonK.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonK.setText("K");

        pd_jRadioButtonF.setBackground(new java.awt.Color(102, 102, 102));
        pd_buttonGroupTemperatura.add(pd_jRadioButtonF);
        pd_jRadioButtonF.setForeground(new java.awt.Color(255, 255, 255));
        pd_jRadioButtonF.setText("°F");

        pd_jLabelC.setBackground(new java.awt.Color(102, 102, 102));
        pd_jLabelC.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelC.setText("Stopni Celcujsza");

        pd_jTextFieldC.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldC.setMaximumSize(new java.awt.Dimension(20, 111));
        pd_jTextFieldC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldCActionPerformed(evt);
            }
        });

        pd_jLabelK.setBackground(new java.awt.Color(102, 102, 102));
        pd_jLabelK.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelK.setText("Stopni Kelvina");

        pd_jTextFieldK.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldK.setMaximumSize(new java.awt.Dimension(20, 111));
        pd_jTextFieldK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldKActionPerformed(evt);
            }
        });

        pd_jButtonPrzeliczTemp.setBackground(new java.awt.Color(102, 102, 102));
        pd_jButtonPrzeliczTemp.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButtonPrzeliczTemp.setText("Przelicz");
        pd_jButtonPrzeliczTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonPrzeliczTempActionPerformed(evt);
            }
        });

        pd_jTextFieldF.setBackground(new java.awt.Color(153, 153, 153));
        pd_jTextFieldF.setMaximumSize(new java.awt.Dimension(20, 111));
        pd_jTextFieldF.setName(""); // NOI18N
        pd_jTextFieldF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jTextFieldFActionPerformed(evt);
            }
        });

        pd_jLabelF.setBackground(new java.awt.Color(102, 102, 102));
        pd_jLabelF.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd_jLabelF.setText("Stopni Fahrenheita");

        javax.swing.GroupLayout pd_jPanelTemperaturyLayout = new javax.swing.GroupLayout(pd_jPanelTemperatury);
        pd_jPanelTemperatury.setLayout(pd_jPanelTemperaturyLayout);
        pd_jPanelTemperaturyLayout.setHorizontalGroup(
            pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pd_jLabelWartJednTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pd_jTextFieldWpiszTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pd_jLabelPrzelJednTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pd_jPanelTemperaturyLayout.createSequentialGroup()
                                .addComponent(pd_jRadioButtonC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pd_jRadioButtonK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pd_jRadioButtonF)
                                .addGap(33, 33, 33)))
                        .addGap(5, 5, 5))
                    .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pd_jSeparator2))
                    .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pd_jLabelC, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(pd_jTextFieldC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pd_jTextFieldK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pd_jLabelK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pd_jLabelF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pd_jTextFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(pd_jButtonPrzeliczTemp)
                .addGap(0, 154, Short.MAX_VALUE))
        );
        pd_jPanelTemperaturyLayout.setVerticalGroup(
            pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jLabelWartJednTemp)
                    .addComponent(pd_jLabelPrzelJednTemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jTextFieldWpiszTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jRadioButtonC)
                    .addComponent(pd_jRadioButtonK)
                    .addComponent(pd_jRadioButtonF))
                .addGap(14, 14, 14)
                .addComponent(pd_jButtonPrzeliczTemp)
                .addGap(18, 18, 18)
                .addComponent(pd_jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                            .addComponent(pd_jLabelC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pd_jTextFieldC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pd_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pd_jPanelTemperaturyLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(pd_jTextFieldK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pd_jLabelK, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pd_jLabelF)
                    .addGroup(pd_jPanelTemperaturyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pd_jTextFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pd_jTabbedPaneMain.addTab("Jednostki temperatury", pd_jPanelTemperatury);

        javax.swing.GroupLayout pd_jPanelLayout = new javax.swing.GroupLayout(pd_jPanel);
        pd_jPanel.setLayout(pd_jPanelLayout);
        pd_jPanelLayout.setHorizontalGroup(
            pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pd_jLabelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pd_jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pd_jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pd_jPanelLayout.setVerticalGroup(
            pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pd_jLabelMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(pd_jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

        pd_jMenuPlik.setText("Plik");

        pd_jMenuItemHistoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        pd_jMenuItemHistoria.setText("Pokaz Historie");
        pd_jMenuItemHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jMenuItemHistoriaActionPerformed(evt);
            }
        });
        pd_jMenuPlik.add(pd_jMenuItemHistoria);

        pd_jMenuItemZamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        pd_jMenuItemZamknij.setText("Zamknij");
        pd_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jMenuItemZamknijActionPerformed(evt);
            }
        });
        pd_jMenuPlik.add(pd_jMenuItemZamknij);

        jMenuBar1.add(pd_jMenuPlik);

        pd_jMenuOprogramie.setText("O programie");

        pd_jMenuItemOpis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        pd_jMenuItemOpis.setText("Opis");
        pd_jMenuItemOpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jMenuItemOpisActionPerformed(evt);
            }
        });
        pd_jMenuOprogramie.add(pd_jMenuItemOpis);

        jMenuBar1.add(pd_jMenuOprogramie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pd_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pd_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pd_jTextFieldWpiszDlugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldWpiszDlugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldWpiszDlugActionPerformed

    private void pd_jRadioButtonMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jRadioButtonMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jRadioButtonMMActionPerformed

    private void pd_jTextFieldMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldMMActionPerformed

    private void pd_jTextFieldCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldCMActionPerformed

    private void pd_jTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldMActionPerformed

    private void pd_jTextFieldKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldKMActionPerformed

    private void pd_jButtonPrzeliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonPrzeliczActionPerformed
        Dlugosci();
        DlugZapis();
    }//GEN-LAST:event_pd_jButtonPrzeliczActionPerformed

    private void pd_jTextFieldDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldDMActionPerformed

    private void pd_jTextFieldWpiszTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldWpiszTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldWpiszTempActionPerformed

    private void pd_jRadioButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jRadioButtonCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jRadioButtonCActionPerformed

    private void pd_jTextFieldCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldCActionPerformed

    private void pd_jTextFieldKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldKActionPerformed

    private void pd_jButtonPrzeliczTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonPrzeliczTempActionPerformed
       Temperatura();
       TempZapis();
    }//GEN-LAST:event_pd_jButtonPrzeliczTempActionPerformed

    private void pd_jTextFieldFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jTextFieldFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_jTextFieldFActionPerformed

    private void pd_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_pd_jMenuItemZamknijActionPerformed

    private void pd_jMenuItemOpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jMenuItemOpisActionPerformed
        JOptionPane.showMessageDialog(this,"Program oblicza jednostki dlugosci i temperatury :)");
    }//GEN-LAST:event_pd_jMenuItemOpisActionPerformed

    private void pd_jMenuItemHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jMenuItemHistoriaActionPerformed
        Historia();
    }//GEN-LAST:event_pd_jMenuItemHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrzeliczanieJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrzeliczanieJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrzeliczanieJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrzeliczanieJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrzeliczanieJednostek().setVisible(true);
            }
        });
    }
    
    private void Dlugosci(){ 
        String wpisana = pd_jTextFieldWpiszDlug.getText();
        Double zmieniona = Double.parseDouble(wpisana);
            
        if(pd_jRadioButtonMM.isSelected()){
            String mm=Double.toString(zmieniona);
            String cm=Double.toString(zmieniona*0.1);
            String dm=Double.toString(zmieniona*0.01);
            String m=Double.toString(zmieniona*0.001);
            String km=Double.toString(zmieniona*0.000001);
            
            pd_jTextFieldMM.setText(""+mm);
            pd_jTextFieldCM.setText(""+cm);
            pd_jTextFieldDM.setText(""+dm);
            pd_jTextFieldM.setText(""+m);
            pd_jTextFieldKM.setText(""+km);
            
        }else if(pd_jRadioButtonCM.isSelected()){
            String mm=Double.toString(zmieniona*10);
            String cm=Double.toString(zmieniona);
            String dm=Double.toString(zmieniona*0.1);
            String m=Double.toString(zmieniona*0.01);
            String km=Double.toString(zmieniona*0.00001);
            
            pd_jTextFieldMM.setText(""+mm);
            pd_jTextFieldCM.setText(""+cm);
            pd_jTextFieldDM.setText(""+dm);
            pd_jTextFieldM.setText(""+m);
            pd_jTextFieldKM.setText(""+km);
            
        }else if(pd_jRadioButtonDM.isSelected()){
            String mm=Double.toString(zmieniona*100);
            String cm=Double.toString(zmieniona*10);
            String dm=Double.toString(zmieniona);
            String m=Double.toString(zmieniona*0.1);
            String km=Double.toString(zmieniona*0.0001);
            
            pd_jTextFieldMM.setText(""+mm);
            pd_jTextFieldCM.setText(""+cm);
            pd_jTextFieldDM.setText(""+dm);
            pd_jTextFieldM.setText(""+m);
            pd_jTextFieldKM.setText(""+km);
            
        }else if(pd_jRadioButtonM.isSelected()){
            String mm=Double.toString(zmieniona*1000);
            String cm=Double.toString(zmieniona*100);
            String dm=Double.toString(zmieniona*10);
            String m=Double.toString(zmieniona);
            String km=Double.toString(zmieniona*0.001);
            
            pd_jTextFieldMM.setText(""+mm);
            pd_jTextFieldCM.setText(""+cm);
            pd_jTextFieldDM.setText(""+dm);
            pd_jTextFieldM.setText(""+m);
            pd_jTextFieldKM.setText(""+km);
            
        }else if(pd_jRadioButtonKM.isSelected()){
            String mm=Double.toString(zmieniona*1000000);
            String cm=Double.toString(zmieniona*100000);
            String dm=Double.toString(zmieniona*10000);
            String m=Double.toString(zmieniona*1000);
            String km=Double.toString(zmieniona);
            
            pd_jTextFieldMM.setText(""+mm);
            pd_jTextFieldCM.setText(""+cm);
            pd_jTextFieldDM.setText(""+dm);
            pd_jTextFieldM.setText(""+m);
            pd_jTextFieldKM.setText(""+km);
            
            
            
        }
    }
    
    private void Temperatura(){
        String wpisana = pd_jTextFieldWpiszTemp.getText();
        Double zmieniona = Double.parseDouble(wpisana);
        if(pd_jRadioButtonC.isSelected()){
            String C=Double.toString(zmieniona);
            String K=Double.toString(zmieniona+273);
            String F=Double.toString((zmieniona*9/5)+32);
            
            pd_jTextFieldC.setText(""+C);
            pd_jTextFieldK.setText(""+K);
            pd_jTextFieldF.setText(""+F);
            
        }else if(pd_jRadioButtonK.isSelected()){
            String C=Double.toString(zmieniona-273);
            String K=Double.toString(zmieniona);
            String F=Double.toString(((zmieniona-273)*9/5)+32);
            
            pd_jTextFieldC.setText(""+C);
            pd_jTextFieldK.setText(""+K);
            pd_jTextFieldF.setText(""+F);
            
        }else if(pd_jRadioButtonF.isSelected()){
            String C=Double.toString(5*(zmieniona - 32)/9);
            String K=Double.toString((5*(zmieniona - 32)/9)+273);
            String F=Double.toString(zmieniona);
            
            pd_jTextFieldC.setText(""+C);
            pd_jTextFieldK.setText(""+K);
            pd_jTextFieldF.setText(""+F);
            
        }
    }
    
    private void DlugZapis(){
        File f = new File("zapis.txt");
        FileWriter fw;
        try {
            fw = new FileWriter(f,true);
            fw.append("o;"+pd_jTextFieldMM.getText()+"mm;"+pd_jTextFieldCM.getText()+"cm;"+pd_jTextFieldDM.getText()+"dm;"+pd_jTextFieldM.getText()+"m;"+pd_jTextFieldKM.getText()+"km\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(PrzeliczanieJednostek.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void TempZapis(){
        File f = new File("zapis.txt");
        FileWriter fw;
        try {
            fw = new FileWriter(f,true);
            fw.append("t;"+pd_jTextFieldC.getText()+"°C;"+pd_jTextFieldK.getText()+"K;"+pd_jTextFieldF.getText()+"°F\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(PrzeliczanieJednostek.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Historia(){
        File f = new File("zapis.txt");
        try {
            String Tekst = "";
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                Tekst = Tekst+"\n"+sc.nextLine();
            }
            JOptionPane.showMessageDialog(this,Tekst);
        }
        catch(FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.ButtonGroup pd_buttonGroupDlugosci;
    private javax.swing.ButtonGroup pd_buttonGroupTemperatura;
    private javax.swing.JButton pd_jButtonPrzelicz;
    private javax.swing.JButton pd_jButtonPrzeliczTemp;
    private javax.swing.JLabel pd_jLabelC;
    private javax.swing.JLabel pd_jLabelCM;
    private javax.swing.JLabel pd_jLabelDM;
    private javax.swing.JLabel pd_jLabelF;
    private javax.swing.JLabel pd_jLabelK;
    private javax.swing.JLabel pd_jLabelKM;
    private javax.swing.JLabel pd_jLabelM;
    private javax.swing.JLabel pd_jLabelMM;
    private javax.swing.JLabel pd_jLabelMain;
    private javax.swing.JLabel pd_jLabelPrzelJednDlug;
    private javax.swing.JLabel pd_jLabelPrzelJednTemp;
    private javax.swing.JLabel pd_jLabelWartJednDlug;
    private javax.swing.JLabel pd_jLabelWartJednTemp;
    private javax.swing.JMenuItem pd_jMenuItemHistoria;
    private javax.swing.JMenuItem pd_jMenuItemOpis;
    private javax.swing.JMenuItem pd_jMenuItemZamknij;
    private javax.swing.JMenu pd_jMenuOprogramie;
    private javax.swing.JMenu pd_jMenuPlik;
    private javax.swing.JPanel pd_jPanel;
    private javax.swing.JPanel pd_jPanelDlugosci;
    private javax.swing.JPanel pd_jPanelTemperatury;
    private javax.swing.JRadioButton pd_jRadioButtonC;
    private javax.swing.JRadioButton pd_jRadioButtonCM;
    private javax.swing.JRadioButton pd_jRadioButtonDM;
    private javax.swing.JRadioButton pd_jRadioButtonF;
    private javax.swing.JRadioButton pd_jRadioButtonK;
    private javax.swing.JRadioButton pd_jRadioButtonKM;
    private javax.swing.JRadioButton pd_jRadioButtonM;
    private javax.swing.JRadioButton pd_jRadioButtonMM;
    private javax.swing.JSeparator pd_jSeparator1;
    private javax.swing.JSeparator pd_jSeparator2;
    private javax.swing.JTabbedPane pd_jTabbedPaneMain;
    private javax.swing.JTextField pd_jTextFieldC;
    private javax.swing.JTextField pd_jTextFieldCM;
    private javax.swing.JTextField pd_jTextFieldDM;
    private javax.swing.JTextField pd_jTextFieldF;
    private javax.swing.JTextField pd_jTextFieldK;
    private javax.swing.JTextField pd_jTextFieldKM;
    private javax.swing.JTextField pd_jTextFieldM;
    private javax.swing.JTextField pd_jTextFieldMM;
    private javax.swing.JTextField pd_jTextFieldWpiszDlug;
    private javax.swing.JTextField pd_jTextFieldWpiszTemp;
    // End of variables declaration//GEN-END:variables
}
