/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.pawel.domagala.domagalapawel_listazakupow;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author domag
 */
public class domagalapawel_listazakupow extends javax.swing.JFrame {

    /**
     * Creates new form domagalapawel_listazakupow
     */
    public domagalapawel_listazakupow() {
        initComponents();
        addKeyListenerCoKupiles();
        addKeyListenerjPodajWartosc();
        addKeyListenerData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelWprowadz = new javax.swing.JPanel();
        jLabelWpiszCoKupiles = new javax.swing.JLabel();
        jTextFieldWpiszCoKupiles = new javax.swing.JTextField();
        jLabelPodajWartosc = new javax.swing.JLabel();
        jTextFieldPodajWartosc = new javax.swing.JTextField();
        jLabelZakupy = new javax.swing.JLabel();
        jLabelTypTowaru = new javax.swing.JLabel();
        jComboBoxTypTowaru = new javax.swing.JComboBox<>();
        jLabelDataZakupu = new javax.swing.JLabel();
        jTextFieldDataZakupu = new javax.swing.JTextField();
        jButtonZapisz = new javax.swing.JButton();
        jLabelWydatkiDzisiaj = new javax.swing.JLabel();
        jTextFieldWydatkiDzisiaj = new javax.swing.JTextField();
        jLabelWydatkiTydzien = new javax.swing.JLabel();
        jTextFieldWydatkiTydzien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaZakupy = new javax.swing.JTextArea();
        jPanelLista = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelWpiszCoKupiles.setText("Wpisz co kupiłeś");

        jTextFieldWpiszCoKupiles.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextFieldWpiszCoKupiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWpiszCoKupilesActionPerformed(evt);
            }
        });
        jTextFieldWpiszCoKupiles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldWpiszCoKupilesKeyTyped(evt);
            }
        });

        jLabelPodajWartosc.setText("Podaj wartosć");

        jTextFieldPodajWartosc.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        jLabelZakupy.setText("Dzisiejsze zakupy");

        jLabelTypTowaru.setText("Typ zakupionego towaru");

        jComboBoxTypTowaru.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jComboBoxTypTowaru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelDataZakupu.setText("Data zakupu");

        jTextFieldDataZakupu.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        jButtonZapisz.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jButtonZapisz.setText("Zapisz");
        jButtonZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapiszActionPerformed(evt);
            }
        });

        jLabelWydatkiDzisiaj.setText("Wydatki z dzisiaj:");

        jTextFieldWydatkiDzisiaj.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        jLabelWydatkiTydzien.setText("Wydatki z tygodnia:");

        jTextFieldWydatkiTydzien.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        jTextAreaZakupy.setColumns(20);
        jTextAreaZakupy.setRows(5);
        jScrollPane1.setViewportView(jTextAreaZakupy);

        javax.swing.GroupLayout jPanelWprowadzLayout = new javax.swing.GroupLayout(jPanelWprowadz);
        jPanelWprowadz.setLayout(jPanelWprowadzLayout);
        jPanelWprowadzLayout.setHorizontalGroup(
            jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelZakupy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                            .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelWpiszCoKupiles, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jTextFieldWpiszCoKupiles))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelPodajWartosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPodajWartosc))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTypTowaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTypTowaru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWydatkiDzisiaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addComponent(jLabelWydatkiTydzien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23)))
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataZakupu, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonZapisz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDataZakupu)))
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldWydatkiDzisiaj)
                            .addComponent(jTextFieldWydatkiTydzien))))
                .addContainerGap())
        );
        jPanelWprowadzLayout.setVerticalGroup(
            jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWpiszCoKupiles)
                            .addComponent(jLabelPodajWartosc)
                            .addComponent(jLabelTypTowaru)
                            .addComponent(jLabelDataZakupu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldWpiszCoKupiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPodajWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTypTowaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabelZakupy))
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addComponent(jTextFieldDataZakupu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonZapisz)))
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWydatkiDzisiaj)
                            .addComponent(jTextFieldWydatkiDzisiaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWydatkiTydzien)
                            .addComponent(jTextFieldWydatkiTydzien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane.addTab("Wprowadź zakupy", jPanelWprowadz);

        javax.swing.GroupLayout jPanelListaLayout = new javax.swing.GroupLayout(jPanelLista);
        jPanelLista.setLayout(jPanelListaLayout);
        jPanelListaLayout.setHorizontalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jPanelListaLayout.setVerticalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Lista zakupów", jPanelLista);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldWpiszCoKupilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWpiszCoKupilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWpiszCoKupilesActionPerformed

    private void jTextFieldWpiszCoKupilesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldWpiszCoKupilesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWpiszCoKupilesKeyTyped

    private void jButtonZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapiszActionPerformed
        Button();
    }//GEN-LAST:event_jButtonZapiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(domagalapawel_listazakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(domagalapawel_listazakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(domagalapawel_listazakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(domagalapawel_listazakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new domagalapawel_listazakupow().setVisible(true);
            }
        });
    }
    
    private void addKeyListenerCoKupiles(){
        jTextFieldWpiszCoKupiles.addKeyListener(new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
              char ch = e.getKeyChar();
                if((ch >= 65 && ch <= 90) || (ch >= 97 && ch <= 122) || ch == 32 || ch == 8){
                    jTextFieldWpiszCoKupiles.setEditable(true);
                    System.out.println("Nacisnieto znak "+ch);
                }else{
                    jTextFieldWpiszCoKupiles.setEditable(false);
                }  
            }

            @Override
            public void keyPressed(KeyEvent e) {
                //System.out.println("2 keyPressed: "+e.getKeyChar());
            }

            @Override
            public void keyReleased(KeyEvent e) {
                //System.out.println("3 keyReleased: "+e.getKeyChar());
            }
        });           
    }
    private void addKeyListenerData(){
      jTextFieldDataZakupu.addKeyListener(new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch >= '0' && ch <= '9' || ch==KeyEvent.VK_BACK_SPACE || ch == 45){
                    jTextFieldDataZakupu.setEditable(true);
                    System.out.println("Nacisnieto cyfre "+ch);
                }else{
                    jTextFieldDataZakupu.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {

            }
        });  
    }
    
    private void addKeyListenerjPodajWartosc(){
        jTextFieldPodajWartosc.addKeyListener(new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch >= '0' && ch <= '9' || ch== 32 ){
                    jTextFieldPodajWartosc.setEditable(true);
                    System.out.println("Nacisnieto cyfre "+ch);
                }else{
                    jTextFieldPodajWartosc.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {

            }
        });
    }
    
    private void Button(){
        jTextAreaZakupy.setText(jTextAreaZakupy.getText()+jTextFieldWpiszCoKupiles.getText()+";"+jTextFieldPodajWartosc.getText()+";"+jComboBoxTypTowaru.getSelectedItem()+";"+jTextFieldDataZakupu.getText()+"\n");
        jTextFieldWpiszCoKupiles.setText("");
        jTextFieldPodajWartosc.setText("");
        jTextFieldDataZakupu.setText("");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonZapisz;
    private javax.swing.JComboBox<String> jComboBoxTypTowaru;
    private javax.swing.JLabel jLabelDataZakupu;
    private javax.swing.JLabel jLabelPodajWartosc;
    private javax.swing.JLabel jLabelTypTowaru;
    private javax.swing.JLabel jLabelWpiszCoKupiles;
    private javax.swing.JLabel jLabelWydatkiDzisiaj;
    private javax.swing.JLabel jLabelWydatkiTydzien;
    private javax.swing.JLabel jLabelZakupy;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelLista;
    private javax.swing.JPanel jPanelWprowadz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaZakupy;
    private javax.swing.JTextField jTextFieldDataZakupu;
    private javax.swing.JTextField jTextFieldPodajWartosc;
    private javax.swing.JTextField jTextFieldWpiszCoKupiles;
    private javax.swing.JTextField jTextFieldWydatkiDzisiaj;
    private javax.swing.JTextField jTextFieldWydatkiTydzien;
    // End of variables declaration//GEN-END:variables
}
