/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.pawel.domagala.domagala_pawel_13kalkulator;

import java.io.FileNotFoundException;

/**
 *
 * @author domag
 */
public class domagala_pawel_13kalkulator extends javax.swing.JFrame {

    double liczba1;
    double liczba2;
    double wynik;
    String typ;
    
    public domagala_pawel_13kalkulator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pd_jPanel = new javax.swing.JPanel();
        pd_jLabelWynik = new javax.swing.JLabel();
        pd_jButtonPusty = new javax.swing.JButton();
        pd_jButtonPierw = new javax.swing.JButton();
        pd_jButtonPotega = new javax.swing.JButton();
        pd_jButtonDziel = new javax.swing.JButton();
        pd_jButton7 = new javax.swing.JButton();
        pd_jButton8 = new javax.swing.JButton();
        pd_jButton9 = new javax.swing.JButton();
        pd_jButtonMnoz = new javax.swing.JButton();
        pd_jButton4 = new javax.swing.JButton();
        pd_jButton5 = new javax.swing.JButton();
        pd_jButton6 = new javax.swing.JButton();
        pd_jButtonMinus = new javax.swing.JButton();
        pd_jButton1 = new javax.swing.JButton();
        pd_jButton2 = new javax.swing.JButton();
        pd_jButton3 = new javax.swing.JButton();
        pd_jButtonPlus = new javax.swing.JButton();
        pd_jButtonClear = new javax.swing.JButton();
        pd_jButton0 = new javax.swing.JButton();
        pd_jButtonWynik = new javax.swing.JButton();
        pd_jSeparator = new javax.swing.JSeparator();
        pd_jLabelWprow = new javax.swing.JLabel();
        pd_jButtonPrzec = new javax.swing.JButton();
        pd_jLabelWprowWysw = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        pd_jMenuPlik = new javax.swing.JMenu();
        pd_jCheckBoxMenuHistoria = new javax.swing.JCheckBoxMenuItem();
        pd_jMenuItemZamknij = new javax.swing.JMenuItem();
        pd_jMenuTools = new javax.swing.JMenu();
        jMenuDni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pd_jPanel.setBackground(new java.awt.Color(0, 0, 0));

        pd_jLabelWynik.setBackground(new java.awt.Color(0, 0, 0));
        pd_jLabelWynik.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pd_jLabelWynik.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelWynik.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pd_jLabelWynik.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        pd_jButtonPusty.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonPusty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonPusty.setForeground(new java.awt.Color(51, 255, 0));
        pd_jButtonPusty.setToolTipText("");
        pd_jButtonPusty.setBorderPainted(false);

        pd_jButtonPierw.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonPierw.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonPierw.setForeground(new java.awt.Color(102, 255, 51));
        pd_jButtonPierw.setText("√");
        pd_jButtonPierw.setToolTipText("");
        pd_jButtonPierw.setBorderPainted(false);
        pd_jButtonPierw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonPierwActionPerformed(evt);
            }
        });

        pd_jButtonPotega.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonPotega.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonPotega.setForeground(new java.awt.Color(102, 255, 51));
        pd_jButtonPotega.setText("^");
        pd_jButtonPotega.setToolTipText("");
        pd_jButtonPotega.setBorderPainted(false);
        pd_jButtonPotega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonPotegaActionPerformed(evt);
            }
        });

        pd_jButtonDziel.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonDziel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonDziel.setForeground(new java.awt.Color(102, 255, 51));
        pd_jButtonDziel.setText("/");
        pd_jButtonDziel.setToolTipText("");
        pd_jButtonDziel.setBorderPainted(false);
        pd_jButtonDziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonDzielActionPerformed(evt);
            }
        });

        pd_jButton7.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton7.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton7.setText("7");
        pd_jButton7.setToolTipText("");
        pd_jButton7.setBorderPainted(false);
        pd_jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton7ActionPerformed(evt);
            }
        });

        pd_jButton8.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton8.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton8.setText("8");
        pd_jButton8.setToolTipText("");
        pd_jButton8.setBorderPainted(false);
        pd_jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton8ActionPerformed(evt);
            }
        });

        pd_jButton9.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton9.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton9.setText("9");
        pd_jButton9.setToolTipText("");
        pd_jButton9.setBorderPainted(false);
        pd_jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton9ActionPerformed(evt);
            }
        });

        pd_jButtonMnoz.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonMnoz.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonMnoz.setForeground(new java.awt.Color(102, 255, 51));
        pd_jButtonMnoz.setText("*");
        pd_jButtonMnoz.setToolTipText("");
        pd_jButtonMnoz.setBorderPainted(false);
        pd_jButtonMnoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonMnozActionPerformed(evt);
            }
        });

        pd_jButton4.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton4.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton4.setText("4");
        pd_jButton4.setToolTipText("");
        pd_jButton4.setBorderPainted(false);
        pd_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton4ActionPerformed(evt);
            }
        });

        pd_jButton5.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton5.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton5.setText("5");
        pd_jButton5.setToolTipText("");
        pd_jButton5.setBorderPainted(false);
        pd_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton5ActionPerformed(evt);
            }
        });

        pd_jButton6.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton6.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton6.setText("6");
        pd_jButton6.setToolTipText("");
        pd_jButton6.setBorderPainted(false);
        pd_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton6ActionPerformed(evt);
            }
        });

        pd_jButtonMinus.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonMinus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonMinus.setForeground(new java.awt.Color(102, 255, 51));
        pd_jButtonMinus.setText("-");
        pd_jButtonMinus.setToolTipText("");
        pd_jButtonMinus.setBorderPainted(false);
        pd_jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonMinusActionPerformed(evt);
            }
        });

        pd_jButton1.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton1.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton1.setText("1");
        pd_jButton1.setToolTipText("");
        pd_jButton1.setBorderPainted(false);
        pd_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton1ActionPerformed(evt);
            }
        });

        pd_jButton2.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton2.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton2.setText("2");
        pd_jButton2.setToolTipText("");
        pd_jButton2.setBorderPainted(false);
        pd_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton2ActionPerformed(evt);
            }
        });

        pd_jButton3.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton3.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton3.setText("3");
        pd_jButton3.setToolTipText("");
        pd_jButton3.setBorderPainted(false);
        pd_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton3ActionPerformed(evt);
            }
        });

        pd_jButtonPlus.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonPlus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonPlus.setForeground(new java.awt.Color(102, 255, 51));
        pd_jButtonPlus.setText("+");
        pd_jButtonPlus.setToolTipText("");
        pd_jButtonPlus.setBorderPainted(false);
        pd_jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonPlusActionPerformed(evt);
            }
        });

        pd_jButtonClear.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonClear.setForeground(new java.awt.Color(255, 102, 0));
        pd_jButtonClear.setText("C");
        pd_jButtonClear.setToolTipText("");
        pd_jButtonClear.setBorderPainted(false);
        pd_jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonClearActionPerformed(evt);
            }
        });

        pd_jButton0.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButton0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButton0.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButton0.setText("0");
        pd_jButton0.setToolTipText("");
        pd_jButton0.setBorderPainted(false);
        pd_jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButton0ActionPerformed(evt);
            }
        });

        pd_jButtonWynik.setBackground(new java.awt.Color(51, 153, 0));
        pd_jButtonWynik.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonWynik.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButtonWynik.setText("=");
        pd_jButtonWynik.setToolTipText("");
        pd_jButtonWynik.setBorderPainted(false);
        pd_jButtonWynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonWynikActionPerformed(evt);
            }
        });

        pd_jSeparator.setForeground(new java.awt.Color(51, 51, 51));

        pd_jLabelWprow.setBackground(new java.awt.Color(0, 0, 0));
        pd_jLabelWprow.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        pd_jLabelWprow.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pd_jLabelWprow.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        pd_jButtonPrzec.setBackground(new java.awt.Color(51, 51, 51));
        pd_jButtonPrzec.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jButtonPrzec.setForeground(new java.awt.Color(255, 255, 255));
        pd_jButtonPrzec.setText(".");
        pd_jButtonPrzec.setToolTipText("");
        pd_jButtonPrzec.setBorderPainted(false);
        pd_jButtonPrzec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jButtonPrzecActionPerformed(evt);
            }
        });

        pd_jLabelWprowWysw.setBackground(new java.awt.Color(0, 0, 0));
        pd_jLabelWprowWysw.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pd_jLabelWprowWysw.setForeground(new java.awt.Color(255, 255, 255));
        pd_jLabelWprowWysw.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pd_jLabelWprowWysw.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pd_jPanelLayout = new javax.swing.GroupLayout(pd_jPanel);
        pd_jPanel.setLayout(pd_jPanelLayout);
        pd_jPanelLayout.setHorizontalGroup(
            pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pd_jPanelLayout.createSequentialGroup()
                        .addComponent(pd_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pd_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pd_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pd_jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pd_jPanelLayout.createSequentialGroup()
                            .addComponent(pd_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButtonMnoz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pd_jPanelLayout.createSequentialGroup()
                            .addComponent(pd_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pd_jPanelLayout.createSequentialGroup()
                            .addComponent(pd_jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButtonPierw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButtonPotega, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pd_jButtonDziel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pd_jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pd_jPanelLayout.createSequentialGroup()
                        .addComponent(pd_jButtonPusty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pd_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pd_jButtonPrzec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pd_jButtonWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(pd_jPanelLayout.createSequentialGroup()
                .addComponent(pd_jLabelWprow, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pd_jLabelWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pd_jLabelWprowWysw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pd_jPanelLayout.setVerticalGroup(
            pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pd_jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pd_jLabelWprowWysw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jLabelWprow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pd_jLabelWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(pd_jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jButtonPierw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButtonDziel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButtonPotega, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButtonMnoz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pd_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pd_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pd_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pd_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pd_jButtonWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pd_jButtonPrzec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pd_jButtonPusty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pd_jMenuPlik.setText("Plik");

        pd_jCheckBoxMenuHistoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        pd_jCheckBoxMenuHistoria.setSelected(true);
        pd_jCheckBoxMenuHistoria.setText("Zapis historii działań");
        pd_jMenuPlik.add(pd_jCheckBoxMenuHistoria);

        pd_jMenuItemZamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        pd_jMenuItemZamknij.setText("Zamknij");
        pd_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_jMenuItemZamknijActionPerformed(evt);
            }
        });
        pd_jMenuPlik.add(pd_jMenuItemZamknij);

        jMenuBar1.add(pd_jMenuPlik);

        pd_jMenuTools.setText("Tools");

        jMenuDni.setText("Ile dni od obliczenia");
        pd_jMenuTools.add(jMenuDni);

        jMenuBar1.add(pd_jMenuTools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pd_jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pd_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pd_jButtonMnozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonMnozActionPerformed
        liczba1 = Double.parseDouble(pd_jLabelWprow.getText());
        pd_jLabelWprow.setText("");
        typ="*";
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"*");
    }//GEN-LAST:event_pd_jButtonMnozActionPerformed

    private void pd_jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonClearActionPerformed
        pd_jLabelWprow.setText("");
        pd_jLabelWynik.setText("");
        pd_jLabelWprowWysw.setText("");
    }//GEN-LAST:event_pd_jButtonClearActionPerformed

    private void pd_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_pd_jMenuItemZamknijActionPerformed

    private void pd_jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton9ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton9.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"9");
    }//GEN-LAST:event_pd_jButton9ActionPerformed

    private void pd_jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton8ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton8.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"8");
    }//GEN-LAST:event_pd_jButton8ActionPerformed

    private void pd_jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton7ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton7.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"7");
    }//GEN-LAST:event_pd_jButton7ActionPerformed

    private void pd_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton6ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton6.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"6");
    }//GEN-LAST:event_pd_jButton6ActionPerformed

    private void pd_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton5ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton5.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"5");
    }//GEN-LAST:event_pd_jButton5ActionPerformed

    private void pd_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton4ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton4.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"4");
    }//GEN-LAST:event_pd_jButton4ActionPerformed

    private void pd_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton3ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton3.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"3");
    }//GEN-LAST:event_pd_jButton3ActionPerformed

    private void pd_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton2ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton2.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"2");
    }//GEN-LAST:event_pd_jButton2ActionPerformed

    private void pd_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton1ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton1.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"1");
    }//GEN-LAST:event_pd_jButton1ActionPerformed

    private void pd_jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButton0ActionPerformed
        String wpisana = pd_jLabelWprow.getText()+pd_jButton0.getText();
        pd_jLabelWprow.setText(wpisana);
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"0");
    }//GEN-LAST:event_pd_jButton0ActionPerformed

    private void pd_jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonPlusActionPerformed
        liczba1 = Double.parseDouble(pd_jLabelWprow.getText());
        pd_jLabelWprow.setText("");
        typ="+";
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"+");
    }//GEN-LAST:event_pd_jButtonPlusActionPerformed

    private void pd_jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonMinusActionPerformed
        liczba1 = Double.parseDouble(pd_jLabelWprow.getText());
        pd_jLabelWprow.setText("");
        typ="-";
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"-");
    }//GEN-LAST:event_pd_jButtonMinusActionPerformed

    private void pd_jButtonDzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonDzielActionPerformed
        liczba1 = Double.parseDouble(pd_jLabelWprow.getText());
        pd_jLabelWprow.setText("");
        typ="/";
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"/");
    }//GEN-LAST:event_pd_jButtonDzielActionPerformed

    private void pd_jButtonPotegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonPotegaActionPerformed
        liczba1 = Double.parseDouble(pd_jLabelWprow.getText());
        pd_jLabelWprow.setText("");
        typ="^";
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"^");
    }//GEN-LAST:event_pd_jButtonPotegaActionPerformed

    private void pd_jButtonPierwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonPierwActionPerformed
        liczba1 = Double.parseDouble(pd_jLabelWprow.getText());
        pd_jLabelWprow.setText("");
        typ="√";
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+"√");
    }//GEN-LAST:event_pd_jButtonPierwActionPerformed

    private void pd_jButtonWynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonWynikActionPerformed
        String a;
        if(typ == "+"){
            liczba2 = Double.parseDouble(pd_jLabelWprow.getText());
            wynik = liczba1 + liczba2;
            a = String.format("%.2f",wynik);
            pd_jLabelWynik.setText(a);
        }else if(typ == "-"){
            liczba2 = Double.parseDouble(pd_jLabelWprow.getText());
            wynik = liczba1 - liczba2;
            a = String.format("%.2f",wynik);
            pd_jLabelWynik.setText(a);
        }else if(typ == "*"){
            liczba2 = Double.parseDouble(pd_jLabelWprow.getText());
            wynik = liczba1 * liczba2;
            a = String.format("%.2f",wynik);
            pd_jLabelWynik.setText(a);
        }else if(typ == "/"){
            liczba2 = Double.parseDouble(pd_jLabelWprow.getText());
            wynik = liczba1 / liczba2;
            a = String.format("%.2f",wynik);
            try{
                if(liczba2 == 0 || liczba1 == 0){
                    pd_jLabelWynik.setText("Błąd");
                }else{
                    pd_jLabelWynik.setText(a);
                }
            }catch(Exception ex) {
            System.out.println(ex.toString());
            }
        }else if(typ == "√"){
            wynik = Math.sqrt(liczba1);
            a = String.format("%.2f",wynik);
            try{
                if(liczba1 == 0){
                    pd_jLabelWynik.setText("Błąd");
                }else{
                    pd_jLabelWynik.setText(a);
                }
            }catch(Exception ex) {
            System.out.println(ex.toString());
            }
        }else if(typ == "^"){
            liczba2 = Double.parseDouble(pd_jLabelWprow.getText());
            wynik = Math.pow(liczba1,liczba2);
            a = String.format("%.2f",wynik);
            pd_jLabelWynik.setText(a);
        }
    }//GEN-LAST:event_pd_jButtonWynikActionPerformed

    private void pd_jButtonPrzecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_jButtonPrzecActionPerformed
        pd_jLabelWprow.setText(pd_jLabelWprow.getText()+".");
        pd_jLabelWprowWysw.setText(pd_jLabelWprowWysw.getText()+".");
    }//GEN-LAST:event_pd_jButtonPrzecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(domagala_pawel_13kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(domagala_pawel_13kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(domagala_pawel_13kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(domagala_pawel_13kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new domagala_pawel_13kalkulator().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDni;
    private javax.swing.JButton pd_jButton0;
    private javax.swing.JButton pd_jButton1;
    private javax.swing.JButton pd_jButton2;
    private javax.swing.JButton pd_jButton3;
    private javax.swing.JButton pd_jButton4;
    private javax.swing.JButton pd_jButton5;
    private javax.swing.JButton pd_jButton6;
    private javax.swing.JButton pd_jButton7;
    private javax.swing.JButton pd_jButton8;
    private javax.swing.JButton pd_jButton9;
    private javax.swing.JButton pd_jButtonClear;
    private javax.swing.JButton pd_jButtonDziel;
    private javax.swing.JButton pd_jButtonMinus;
    private javax.swing.JButton pd_jButtonMnoz;
    private javax.swing.JButton pd_jButtonPierw;
    private javax.swing.JButton pd_jButtonPlus;
    private javax.swing.JButton pd_jButtonPotega;
    private javax.swing.JButton pd_jButtonPrzec;
    private javax.swing.JButton pd_jButtonPusty;
    private javax.swing.JButton pd_jButtonWynik;
    private javax.swing.JCheckBoxMenuItem pd_jCheckBoxMenuHistoria;
    private javax.swing.JLabel pd_jLabelWprow;
    private javax.swing.JLabel pd_jLabelWprowWysw;
    private javax.swing.JLabel pd_jLabelWynik;
    private javax.swing.JMenuItem pd_jMenuItemZamknij;
    private javax.swing.JMenu pd_jMenuPlik;
    private javax.swing.JMenu pd_jMenuTools;
    private javax.swing.JPanel pd_jPanel;
    private javax.swing.JSeparator pd_jSeparator;
    // End of variables declaration//GEN-END:variables
}
